### ISSUE TITLE
DHCP Code? 

### ISSUE THREAD

**Issue by jamesmontemagno** [iandow/Xamarin.Plugins#1]
Wondering if you were able to commit the code and a license. Would like to add it to our plugins page and also contribute.

**Comment by iandow** [comment]
Unfortunately, I was unable to find the DHCP hooks in needed in mobile platform APIs.  So, essentially, this was an experiment that failed.  I just delisted the nuget package.

**Comment by jamesmontemagno** [comment]
You will have to de-list all the versions :( https://www.nuget.org/packages/Downard.Plugin.DhcpInfo/ as it is still available.

**Comment by iandow** [comment]
Oh.  I just delisted them all.  Thanks for the FYI.
